[package]
name = "gcm-nonceless"
version = "0.1.0"
edition = "2024"
authors = ["Yumechi <yume@yumechi.jp>"]
categories = ["cryptography"]
description = "Decrypts GCM encrypted data without access to the nonce."
license = "Apache-2.0"
repository = "https://github.com/eternal-flame-AD/gcm-nonceless"
keywords = ["cryptanalysis", "gcm", "aes", "aes-gcm"]

[dependencies]
aes = { version = "0.8", default-features = false }
base64 = "0.22"
ctr = { version = "0.9", default-features = false }
ghash = "0.5"

hex = { version = "0.4.3", optional = true }
clap = { version = "4.5", features = ["derive"], optional = true }

[dev-dependencies]
aes-gcm = "0.10"

[features]
default = []
cli = ["dep:clap", "dep:hex"]

[[bin]]
name = "gcm-nonceless-decryptor"
path = "src/main.rs"
required-features = ["cli"]
